name: Embed with sharding

on:
  workflow_dispatch:

jobs:
  embed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [0, 1, 2, 3]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t embed .

      - name: Run Docker Container
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
          SHARD_INDEX: ${{ matrix.shard }}
          TOTAL_SHARDS: 4
        run: docker run -e SECRETS_JSON -e SHARD_INDEX -e TOTAL_SHARDS embed